### ISSUE TITLE
Outcoming RPC, fix

### ISSUE THREAD

**Issue by Romz24** [BrunoBM16/samp-rpc-list#3]
For **ApplyActorAnimation**, **ApplyPlayerAnimation** in the parameters 2 times the variable fDelta is specified, this would be a good fix.

![image](https://user-images.githubusercontent.com/2458113/43663658-03ab657e-9773-11e8-9100-fddfce11ef9b.png)

**Comment by BrunoBM16** [comment]
Fixed, thanks.
